use_frameworks!
source 'https://github.com/RichieZhl/Spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'react-native-masked-view_Example' do
  pod 'react-native-masked-view', :path => '../'

  target 'react-native-masked-view_Tests' do
    inherit! :search_paths

    
  end
end
